### ISSUE TITLE
I am a bored full stack developer looking for interesting ideas

### ISSUE THREAD

**Issue by terthesz** [leios/SoME_Topics#210]
## Portfolio

This might seem weird but I haven't finished any publishable projects yet... (I finished some but they are too weird for the world to see or they aren't web pages). Just to reassure - I will finish a project if I want to I just don't have any good ideas.

## Target topic categories

I don't have a specifi topic in mind. Just something that can be made into a interactive web page.

## Target medium

As I said in the previous category. I am interested in making a interactive web page.

### Contact details

Just reply to this thread

**Comment by Graham853** [comment]
You sound like you have the skills I'm looking for (#213 ) but I don't know if growing leaves interests you...

**Comment by follymath** [comment]
I'm also a full stack dev, but with some domain expertise combinatorics and computational complexity, and I've dabbled in number theory over the years. If you're looking for interesting interactive math projects, I could certainly help feed you interesting possibilities.

What kind of stuff are you interested in? What kinds of itches are you interested in scratching? If you've got time on your hands, you really couldn't go wrong just browsing sources like [observablehq](https://observablehq.com/) -- find something interesting, fork and tinker. You probably already know javascript, so observable's probably a great place to start. It's also a great platform for low-friction collaboration.

If you're looking for something more specific to dive into, I've have tons of material I've accumulated that's just bit-rotting away, and I'm trying to get myself to finally do something with some of it. If modular arithmetic is your thing [here's a perverse take on some well-known objects](https://github.com/leios/SoME_Topics/issues/214).

If you're into bases, there's some wild and seemingly unknown geometry that [I touched on here re: fractional bases](https://github.com/leios/SoME_Topics/issues/203#issuecomment-1172939883), but there's so much more there. For example, an [old desmos toy](https://www.desmos.com/calculator/ckdleysapi) showing how this works to hyperbinary (and higher). But unlike positional or mixed radix notations, there are multiple paths available to a given value in these hyper-bases. In hyperbinary, for instance, the total number of paths is given by the [fusc function](https://rosettacode.org/wiki/Fusc_sequence) -- are there similar counting functions for other hyper-bases?

Also, yes, I know I just suggested that there is one unique representation in standard positional notation -- but doesn't 0.999... = 1? They may evaluate to the same value as polynomials, but they are very different representations -- different kinds of numbers, as equal as the integer `1` and the float `1.0` -- equivalent modulo certain type info, but whether or not to treat them as equivalent is a matter of interpretation.

It's this interplay between the various interpretations that I find fascinating. I could point to even more provocative examples if you're interested. Perhaps my favorite is the two different interpretations of given reduction of 3-SAT used by Manders and Adleman in their proof of the NP-Completeness of finding a modular square root less than a given bound. I'm going to write this one separately, because it's just wild.

If any of this sounds interesting, let me know and I can go into excruciating detail.
