### ISSUE TITLE
Curious producer looking for interesting applied topic

### ISSUE THREAD

**Issue by AndersonDaniel** [leios/SoME_Topics#22]
Hey!

I'm a data scientist with webdev experience, would be happy to produce anything that catches my interest!
I love making interactive stuff and also have some experience making videos, so quite flexible as long as I relate to the topic.

## Portfolio

[Personal blog](https://andersource.dev/) - I wrote quite a few interactive demos and you can get an idea of the sort of topics that interest me

## Target topic categories

Very interested in applied topics. Love optimizations (e.g. really loved these videos: [Algorithmic Redistricting](https://www.youtube.com/watch?v=Lq-Y7crQo44), [Curved basketball hoop always goes in](https://www.youtube.com/watch?v=vtN4tkvcBMA)). Also love algorithmic art.

## Target medium

Anything goes! I'd be happy to get out of the comfort zone and play with a new medium. As I mentioned above I feel very comfortable with interactive webdev, also have experience making videos with code.

### Contact details

daniel@andersource.dev

Cheers!

**Comment by Notnilc-N** [comment]
If you don't know what they are, then you should absolutely look into krylov subspaces.
They're a way to solve large matrix equations (i.e. Ax=b, where A is a matrix, x is an unknown vector, and b is a known vector) efficiently, which is done by projecting the solution vector x onto a lower dimensional subspace, usually denoted K_m. I don't know how technical I can get with the math (K_m is constructed from the cayley-hamilton equation), but this method is REALLY useful since it lets us approximate things like partial differential equations, and it's only of the components of the Jacobian-Free-Newton-Krylov (JFNK) method, which is the leading industry standard for simulating partial differential equations. I've looked online and I can't find any visualizations, but I'm just a very passionate student who only learned about this this semester so you'd be better off talking to a professor or something.

**Comment by benjaminverbeek** [comment]
Hi Daniel,

I have a topic idea that might interest you! It might be slightly less applied than the examples you gave, but the method explained has immense applicability and is practically used everywhere: "How do you actually extract science from data?" or "How maths helps us understand the Universe"
For example: you run a really advanced particle physics experiment, and you have some model theory describing the reaction with some parameters telling you something about the essence of our universe. Given reaction data, how can you find these interesting parameters? I believe most people kind of take this for granted: You make a measurement and *poof* out come numbers representing science.

The concept I have in mind, maximum log likelihood estimation, is really quite simple, and there are some very interesting applications (I have personally worked with particle physics experiments looking for violations of particle - antiparticle symmetry in the universe, but there are many more). I believe this somehow could make science a little more believable for some, as the analysis step becomes less of a black-box. Also, statistics is somewhat underrepresented in the realm of enticing math content (in my opinion), so I believe the impact of new contact could be great! I also believe your past work matches the type of animations I have in mind very well.

Let me know if this sounds interesting and we can exchange contact information!

**Comment by AndersonDaniel** [comment]
@zelosos Thanks, I'll check it out!

Thanks everyone for replying and sending me e-mails, got a few messages so I'm good for now, good luck to everyone!
