### ISSUE TITLE
[Script] Higher dimensions

### ISSUE THREAD

**Issue by NutronStar45** [leios/SoME_Topics#42]
## About the author

I'm a hobbyist interested in mathematics. I know some algebra, linear algebra and trigonometry.

## Quick Summary

These are sorted arbitrarily, suggestions are welcome.
- Explain 2D rotations with matrices
- Explain slicing a 3D object into 2D
- Explain projecting a 3D object into 2D
- Explain 3D rotations with matrices
- Explain the concept of 4D
- Explain the differences between the Euclidean 4D space and the Minkowski spacetime
- Explain slicing a 4D object into 3D
- Explain projecting a 4D object to 3D
- Explain 4D rotations with matrices
- Explain double rotations in 4D
- Explain higher dimensions

The video is like an introduction to the higher dimensions, so its target will likely be people unfamiliar with these. I hope they will get a picture of higher dimensions and wonder about their beauty.

## Target medium

This will be a video.
Currently needing voice-over and editing.

### Contact details

My Discord `NutronStar45#8278`

**Comment by filonik** [comment]
Higher dimensions are always fun, and I like your approach of working upwards from 2D to 3D to 4D...

Given the context, I am guessing you are familiar with this? Just mentioning since it features some of the best interactive 4D visualization that I have seen so far:

https://eater.net/quaternions

It would be cool to build/extend upon that.

**Comment by NutronStar45** [comment]
> Higher dimensions are always fun, and I like your approach of working upwards from 2D to 3D to 4D...
> 
> Given the context, I am guessing you are familiar with this? Just mentioning since it features some of the best interactive 4D visualization that I have seen so far:
> 
> https://eater.net/quaternions
> 
> It would be cool to build/extend upon that.

Quaternions are 4D, but it's not the Euclidean 4D space, so it will not be in the video.

**Comment by filonik** [comment]
I mentioned it due to the general approach towards visualizing 4D space, the specific metric is not really important. There's a lot there that is universally applicable, such as the use of stereographic projection or the ability to select/toggle different sub-spaces. Anyhow, good luck with the video!

**Comment by NutronStar45** [comment]
You can help me with that if you want

**Comment by SimonAndreys** [comment]
On the explanation and visualization of 4D objects, you can draw inspiration from the "dimension" videos :

**Comment by NutronStar45** [comment]
That was a very good explanation indeed
